version: "3.8"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bigdataproject
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: 'VBamcsC9XBpPMLur'
    volumes:
      - bigdata:/var/lib/postgresql/data

  #  db:
  #    image: mysql:8
  #    ports:
  #      - 3306:3306
  #    environment:
  #      MYSQL_ROOT_PASSWORD: 'LN5gZjD6x8FU8PQG'
  #      MYSQL_DATABASE: bigdataproject
  #      MYSQL_USER: bigdata
  #      MYSQL_PASSWORD: 'VBamcsC9XBpPMLur'
  #    volumes:
  #      - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  #      - bigdata:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  bigdata: